### ISSUE TITLE
travix 0.13.1 js failing with travis

### ISSUE THREAD

**Issue by FrancisBourre** [back2dos/travix#116]
0.12.2 works fine, but 0.13.1 stops working with an unexpected token error in run.js file
https://travis-ci.org/DoclerLabs/hexCore/jobs/566671635

Any idea about what should I do?

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
The command "haxelib run travix $HAXE_TARGET" exited with 1.

**Comment by back2dos** [comment]
We switched to puppeteer and the run script requires ES6, meaning you have to target a high enough node version. There's some docs on how to do that with the [.travis.yaml](https://docs.travis-ci.com/user/languages/javascript-with-nodejs#specifying-nodejs-versions) or you can try running something along the lines of [`nvm install node`](https://github.com/nvm-sh/nvm#usage) during the install stage.

**Comment by FrancisBourre** [comment]
Thanks, I installed node 8 and it works fine now.
